### ISSUE TITLE
Downloading datatable after statistics does not work

### ISSUE THREAD

**Issue by okendojo** [JamesGallant/ProVision#10]
I have done the differential analysis and when I try to download the  `all comparison` table it doesnt work. Could you kindly advice on this? I look forward to hearing from you soon

**Comment by JamesGallant** [comment]
Hi Javan, 

Lets see if we can fix this for you. 

Could you elaborate? There are two ways to download files, there is the download option on the page and another option which is download tables. To download all the comparisons you need to open download tables dropdown comparison and choose all comparsions, followed by the  file type. The click the download button in the side panel, not the download button on the main dashboard. This will download a zip folder with your comparisons. I have just tested this functionality using google chrome. Can you do the same and confirm whether or not it works. 

If it not clear, let me know.
