### ISSUE TITLE
Question -- how effect size is calculated

### ISSUE THREAD

**Issue by elvavidya** [JamesGallant/ProVision#17]
Thank you very much for this awesome and user-friendly analyses tool! Could you please clarify how the 'effect size' is calculated in ProVision? From the tutorial, I'm aware that effect size means fold change and is expressed as a logarithmic value, but I'd like to better understand what is it based on? I have few cases of proteins that are not significantly different from my control, but has larger effect sizes compared to some proteins that are considered significantly upregulated. Any insights or directions to more detailed explanations would be really appreciated! Thanks again.

**Comment by JamesGallant** [comment]
Hi sorry it took so long to get back to you. Fold change is calculated by Limma, the short version is that its simply the logarithmic difference between the means. Its possible to have a big fold change without it being significantly different, this means that you have variability in the proteins within replicates which leads to it presenting as non-significant.
