### ISSUE TITLE
Error in Line 771

### ISSUE THREAD

**Issue by kronigert** [JamesGallant/ProVision#5]
Hey James,
thank you for prividing ProVision. I just downloaded the local version and got a error message that there is no file "analytics.html" which is looked up by the program in line 771. When I delete the line as in previous versions of ProVision, the app is up and running.

All the best,
Tobi

**Comment by JamesGallant** [comment]
Hi Tobi Thanks for letting me know! I'm the only dev on this so its hard to catch all the bugs, I really appreciate it. I removed the line in the master branch. 

Cheers.
