### ISSUE TITLE
Error: duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by juliabandura** [JamesGallant/ProVision#8]
Hi James,

Thanks for making this - ProVision looks like an amazing tool for proteomics analysis and is a joy to use.

I'm having an issue where I can't do the statistical analysis portion because I have duplicate row names - not sure what's happening there. 

Do you have any suggestions for a fix/wrangling of my data I could do before uploading? 

Thanks,
Julia

**Comment by juliabandura** [comment]
![image](https://user-images.githubusercontent.com/32461709/89691693-948c1c80-d8d7-11ea-822f-3f9f98a4538d.png)

**Comment by JamesGallant** [comment]
Hi Julia, 

Sorry that I only get to this now! Let me know if you still have this issue.

Do you also get this error after filtering your data or only at the statistics step?  While I'm not quite sure why it does this during the statistics steps, there are some places where such a bug might slip by. If it's only in the statistics step then it this can occur if you gave your samples the same name when searching in MaxQuant. Check that the "ID" Column under "data handling" and "assign groups" has no duplication's.
