### ISSUE TITLE
Adding function to highlight differentially expressed proteins in volcano plots

### ISSUE THREAD

**Issue by okendojo** [JamesGallant/ProVision#9]
Thanks for this great free online analysis  platform. Could you add an option of labelling the most significant proteins from the volcano plot because some reviewers prefer to see the actual proteins which are differentially expressed in volcano plot.

**Comment by JamesGallant** [comment]
Hi Javan, 

This option is available in ProVision. Under Volcano plots after you have calculated the stats there is a secondary dropdown menu named `label significant proteins`. Here you can label the top up and/or down regulated proteins. 

This is extracted from the fasta header of the proteinGroups.txt file so it will be labelled with the gene names you have there. 

If this is not what you meant let me know.

**Comment by JamesGallant** [comment]
@javanOkendo 

Hi Javan, 

I am going to assume that all went well, feel free to open another request if needed.

**Comment by okendojo** [comment]
All went on well. Thanks for a great tool
